### ISSUE TITLE
About code release

### ISSUE THREAD

**Issue by Roywangj** [monster-ghost/MonoDistill#1]
Hi! Thank you for your work.

I want to know when will you release the code?

**Comment by monster-ghost** [comment]
Thank you very much for your interest in our work. We will release the code by the beginning of ICLR'22.

**Comment by Roywangj** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
