### ISSUE TITLE
Is KD code of GUPNet public?

### ISSUE THREAD

**Issue by Senwang98** [monster-ghost/MonoDistill#10]
@czy341181 @monster-ghost @xinzhuma
Sorry for disturb, I notice that you done KD on GUPNet in paper.
Could you provide one version of GUPNet? (I feel confused about GUPNet's head and HTL when distillling)
I want to apply KD to GUPNet, can you help me?

**Comment by Senwang98** [comment]
Spend one day to meet the need of GUPNet, has achieved much higher mAP than that reported in MonoDisill paper.

**Comment by xinzhuma** [comment]
Temporally we don't have enough time to re-organize the codes for GUPNet. We are glad to hear that you have implemented it with a better performance.

**Comment by Senwang98** [comment]
@czy341181 @xinzhuma 
请教一下你们当时在MonoDistill提交kitti的时候，Teacher模型有基于**Trainval split**重新训练嘛？还是说直接用消融实验的那个仅基于**Train split**训练的teacher？

**Comment by xinzhuma** [comment]
teacher始终是在train split训练的那个。student需要在trainval重新训练

2023年1月12日 下午11:00，Egqawkq ***@***.******@***.***>> 写道：



@xinzhuma<https://github.com/xinzhuma>
xinzhu佬，请教一下你们当时在MonoDistill提交kitti的时候，Teacher模型有基于Trainval split重新训练嘛？还是说直接用消融实验的那个仅基于Train split训练的teacher？
