### ISSUE TITLE
How to test the model?

### ISSUE THREAD

**Issue by ClacYc** [monster-ghost/MonoDistill#3]
I am sorry to bother you.I met some basic issues while reproduce your model...
My confusion is :How to get the results by **inference in test set** and provided weight **distill.pth**?
Trying to modify the 'val' to 'test' in **dataloader_helper.py** but does not work because code needs depth maps(But I have test imgs only).
How to solve this?
Thank you !

**Comment by monster-ghost** [comment]
Sorry for that, this is our negligence. We will upload the modified code.
You can comment out related code about depth map in kitti_dataset.py

**Comment by ClacYc** [comment]
> Sorry for that, this is our negligence. We will upload the modified code. You can comment out related code about depth map in kitti_dataset.py
