### ISSUE TITLE
How many affinity maps are you using to get L_{sf}?

### ISSUE THREAD

**Issue by zjwzcx** [monster-ghost/MonoDistill#4]
Hi, Zhiyu! Thanks for your awesome work!

According to the Eq (1) and Eq(2) in your paper, it seems that we should compute **K^2 affinity maps** to get L_{sf}. However, you may only compute **K affinity maps**, which are A_{i, i} where i ∈{1, 2, ..., K}, by function `compute_backbone_resize_affinity_loss()` in `feature_distill_loss.py`. So, how many affinity maps are you using to get L_{sf} in your experiments?

Function `compute_backbone_resize_affinity_loss()` is as follows:

```
 def compute_backbone_resize_affinity_loss(features_preds, features_targets):    # scene-level, feature space
    feature_ditill_loss = 0.0
    resize_shape = features_preds[-1].shape[-2:]    # last feature map
    if isinstance(features_preds, list):
        for i in range(len(features_preds)):  # 1/8   1/16   1/32
            feature_target = features_targets[i].detach()
            feature_pred = features_preds[i]

            # resize to the shape of the last feature map
            B, C, H, W = feature_pred.shape
            feature_pred_down = F.interpolate(feature_pred, size=resize_shape, mode="bilinear")
            feature_target_down = F.interpolate(feature_target, size=resize_shape, mode="bilinear")

            feature_target_down = feature_target_down.reshape(B, C, -1)
            depth_affinity = torch.bmm(feature_target_down.permute(0, 2, 1), feature_target_down)

            feature_pred_down = feature_pred_down.reshape(B, C, -1)
            rgb_affinity = torch.bmm(feature_pred_down.permute(0, 2, 1), feature_pred_down)

            feature_ditill_loss = feature_ditill_loss + F.l1_loss(rgb_affinity, depth_affinity, reduction='mean') / B

    else:
        raise NotImplementedError

    return feature_ditill_loss
```

**Comment by zjwzcx** [comment]
@monster-ghost Look forward to your reply, thanks!

**Comment by czy341181** [comment]
Hi, thanks for your attention.

The shape of affinity map is hw * hw， which means that each pixel will calculate an affinity map with other pixels. Therefore, we can obtain hw affinty maps.

In our Eq(2), i and j represent row and column index. Therefore, we should compute K^2 (H*W)affinity maps

**Comment by monster-ghost** [comment]
Hi, thanks for your attention.

The shape of affinity map is hw * hw， which means that each pixel will calculate an affinity map with other pixels. Therefore, we can obtain hw affinty maps.

**Comment by zjwzcx** [comment]
> Hi, thanks for your attention.
> 
> The shape of affinity map is hw * hw， which means that each pixel will calculate an affinity map with other pixels. Therefore, we can obtain hw affinty maps.
> 
> In our Eq(2), i and j represent row and column index. Therefore, we should compute K^2 (H*W)affinity maps

Thanks for your kind reply! I‘m sorry to say that I didn't fully understand your answer. :(

I can understand that the shape of affinity map is hw * hw. Why does it mean that `we can obtain hw affinty maps`?

In your code as shown in my problem descripsion, the program should do K loops, right? However, it seems that we only compute `(A_{i, i}^s - A_{i, i}^t)` in the i_th loop. If so, we only compute K affinity maps instead of K^2?

**Comment by zjwzcx** [comment]
@monster-ghost Sorry to interrupt you again. I'm concerned that you may not have seen the update in question. (I really want to know more about your good work.

**Comment by monster-ghost** [comment]
Sorry for not replying you in time(We are busy for another work). 
I don't get your point. 
Each pixel will calculate an affinity map with other pixels.
A_{i, j} means the affinity of i_th feature veature and j_th feature veature. We do it K times and obtain affinity map between i_th feature verctor and other feature vercors. After that, to we do it K times again, we can obtain hw*hw affinity map.

**Comment by zjwzcx** [comment]
> Sorry for not replying you in time(We are busy for another work). I don't get your point. Each pixel will calculate an affinity map with other pixels. A_{i, j} means the affinity of i_th feature veature and j_th feature veature. We do it K times and obtain affinity map between i_th feature verctor and other feature vercors. After that, to we do it K times again, we can obtain hw*hw affinity map.

您好，感谢解答，为了便于理解，我直接用中文问哈。

**我能够理解的是：**
1. affinity map A_{i, j}由feature vector i和feature vector j计算得到，每个affinity map空间维度为 hw * hw

**我不能理解的是：**
1. i_th feature veature 和 j_th feature veature (i != j) 的计算在程序中是如何实现的？我在问题中附上的代码只执行了K次循环，而第i次循环中，feature vector i似乎只会和自身的转置计算得到的affinity map A_{i, i} (对应代码为 `affinity = torch.bmm(vector.permute(0,2,1), vector)` )。那么K次循环不是只能得到A_{i, i}, i=0,1, ..., K-1吗？

期待您的回复，谢谢！ :)

**Comment by monster-ghost** [comment]
feature vector是一个pixel的特征， C维度的。       A_i,j表示的是pixel_i和pixel_j的相似度， K次循环后就表示了pixel_i和其他所有像素的相似度（hw）。之后再经过K次,得到hw*hw的affinity matrix

**Comment by zjwzcx** [comment]
> feature vector是一个pixel的特征， C维度的。 A_i,j表示的是pixel_i和pixel_j的相似度， K次循环后就表示了pixel_i和其他所有像素的相似度（hw）。之后再经过K次,得到hw*hw的affinity matrix

Got it. Thanks for your kind reply! I'll close this issue soon. Hope to see your other excellent work soon.
