### ISSUE TITLE
How to train teacher?

### ISSUE THREAD

**Issue by Senwang98** [monster-ghost/MonoDistill#6]
hi, @monster-ghost @xinzhuma
I am trying to train lidar teacher model. 
I change the input of monodle to depth images, but my val mAP is only 20.5.
I change the following code in **kitti_dataset.py**:
<img width="471" alt="image" src="https://user-images.githubusercontent.com/23122139/172033961-b237792c-3d07-4caf-9de1-1c830bebf86a.png">
Can you help me?

**Comment by czy341181** [comment]
So sorry for late reply.  

You can do following step to train LiDARNet.
1.train_helper.py    line 187   input['rgb']-->input 
2.centernet3d.py line 54 input['rgb'] --> input['depth']

**Comment by ZhaoWenjun123** [comment]
> 

I do this, but i get the bad result
2022-06-24 13:14:42,100   INFO  Car AP@0.70, 0.70, 0.70:
bbox AP:69.3763, 60.6825, 59.8643
bev  AP:0.0085, 0.4522, 0.5704
3d   AP:0.0000, 0.2347, 0.3053
aos  AP:57.36, 50.56, 49.88
Car AP_R40@0.70, 0.70, 0.70:
bbox AP:68.8294, 61.3217, 56.6250
bev  AP:0.0023, 0.3731, 0.3137
3d   AP:0.0000, 0.1291, 0.0839
aos  AP:55.38, 49.35, 45.59
Car AP@0.70, 0.50, 0.50:
bbox AP:69.3763, 60.6825, 59.8643
bev  AP:0.3007, 3.8829, 4.2116
3d   AP:0.1922, 3.5909, 3.8613
aos  AP:57.36, 50.56, 49.88
Car AP_R40@0.70, 0.50, 0.50:
bbox AP:68.8294, 61.3217, 56.6250
bev  AP:0.2430, 3.0918, 3.7238
3d   AP:0.1020, 2.1722, 2.6169
aos  AP:55.38, 49.35, 45.59

**Comment by czy341181** [comment]
You can load all checkpoints to check performance.  The training process of LiDARNet is not unstable.

Also;
Some reason is that the mean and variance can be removed(sky may be wrong).
You can remove the operation:
lib/datasets/kitti/kitti_dataset.py line 178
depth_map = (depth_map - self.gt_depth_mean) / self.gt_depth_std

**Comment by Senwang98** [comment]
@czy341181 @monster-ghost @xinzhuma
Do you know how to calculate the mean and std in this repo?
Is there any difference between RGB image's mean/std and LiDAR image's ?
My result is different from that in this repo and I am not sure my processing is right or not.

**Comment by czy341181** [comment]
You can load all checkpoints to check performance.&nbsp; The training process of LiDARNet is not unstable.


Also;
Some reason is that the mean and variance can be removed(sky may be wrong).
You can remove the operation:
lib/datasets/kitti/kitti_dataset.py line 178
depth_map = (depth_map - self.gt_depth_mean) / self.gt_depth_std








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "monster-ghost/MonoDistill"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月24日(星期五) 中午1:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [monster-ghost/MonoDistill] How to train teacher? (Issue #6)





   
I do this, but i get the bad result
 2022-06-24 13:14:42,100   INFO  Car ***@***.***, 0.70, 0.70:
 bbox AP:69.3763, 60.6825, 59.8643
 bev  AP:0.0085, 0.4522, 0.5704
 3d   AP:0.0000, 0.2347, 0.3053
 aos  AP:57.36, 50.56, 49.88
 Car ***@***.***, 0.70, 0.70:
 bbox AP:68.8294, 61.3217, 56.6250
 bev  AP:0.0023, 0.3731, 0.3137
 3d   AP:0.0000, 0.1291, 0.0839
 aos  AP:55.38, 49.35, 45.59
 Car ***@***.***, 0.50, 0.50:
 bbox AP:69.3763, 60.6825, 59.8643
 bev  AP:0.3007, 3.8829, 4.2116
 3d   AP:0.1922, 3.5909, 3.8613
 aos  AP:57.36, 50.56, 49.88
 Car ***@***.***, 0.50, 0.50:
 bbox AP:68.8294, 61.3217, 56.6250
 bev  AP:0.2430, 3.0918, 3.7238
 3d   AP:0.1020, 2.1722, 2.6169
 aos  AP:55.38, 49.35, 45.59

**Comment by Senwang98** [comment]
@czy341181 @monster-ghost @xinzhuma
Sorry for disturb, I notice that you done KD on GUPNet in paper.
Could you provide one version of GUPNet? (I feel confused about GUPNet's head and HTL when distillling)
I want to apply KD to GUPNet, can you help me?
