### ISSUE TITLE
where the code about "depth uncertainty"

### ISSUE THREAD

**Issue by feifeiwei** [monster-ghost/MonoDistill#7]
hello,I found   ***we normalize the confidence of each predicted box using depth uncertainty. In this way, the score has capability of indicating the uncertainty of depth.***
 operation in the paper, but I didn't find the relevant code. Can you tell me where it is ？

**Comment by czy341181** [comment]
So sorry for late reply.  
In decoder_helper.py  line49

You can refer this paper:   https://arxiv.org/pdf/2107.13774.pdf (GUPNet)

**Comment by feifeiwei** [comment]
thanks!
